# Generated by Django 5.0.2 on 2024-02-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
