# Generated by Django 5.0.2 on 2024-02-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_leaves_resources'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'permissions',
            },
        ),
        migrations.AddField(
            model_name='resources',
            name='permissions',
            field=models.ManyToManyField(blank=True, null=True, to='blog.permissions'),
        ),
    ]
